#cloud-config

users:
  - default
  - name: xiaocj
    gecos: Xiao Chuanjiao
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,admin,sudo
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtDR5xBFXZ3oNQlRHeO04v76sNAdoq/qX1+RydUYuzaNkRvRVXycgJs1VsTMB+k+yin1w6lE+OhHX95ajKhIqdQMQQnkp3jeFrTQVA1UabsWMj6eetkL4h49peN/Vw/d4G8WE11OUcHZzr0d/4xEIdvpIVYM/PLukiWMIHp98kMkZTtzeCnB7V4d65eG7lnmaGL7s8ZAH7fP8SihSYNk/3BVZ0I5Qzy52RR/3ueeojisvb35uCFKIkFPTF+JquuTT8shP2jSRNbQNDCsm8JmOZPrXOJQ2kX/wZ00FCqWBOb1n16AobWiDEwGVNk275jFSKn0ZRHIdAUIUMjIBVSDhDRh9QJfsoHbUjuOPz6Xar4IeowPDZq70dVrh5gUmmLcC7rj7F28OFbIxUeaHRmYsdhiVC7beerIkS8wfZAEEioliYakFVlHq+B2y7pnZKL8BmOMy3LnS0lVG9a8eUKzzrxf2VQPjbaUjLTZSfZFpfrzQt7iHF5uvqNDshY6NgRzpj2hmnY5NoiA8X9vMSSJ2Qxu4GOxQko/2NxG2QC5gsl5uwoF//g97yrYBlmeOqFlaIRD3Rnhzyb2ZZwU/uiTlQ0mhWjVu55qOhFQFrQcvI+TDRvF9LNa6EdlxXcN7A826OIpPxdF6IFe49aX9Zxc86eREavmMCCOnfZ9DPWopLiQ== xiaocj@gmail.com
  - name: zookeeper
    gecos: Zookeeper
    groups: users

package_update: true
packages:
  - default-jdk

write_files:
  - path: /zookeeper/myid
    content: |
      1
  - path: /zookeeper/conf/zoo.cfg
    content: |
      tickTime=2000
      initLimit=10
      syncLimit=5
      dataDir=/zookeeper/data
      dataLogDir=/zookeeper/logs
      clientPort=2181
      #ZK集群节点配置，端口号2888用于集群节点之间数据通信，端口号3888用于集群中Leader选举
      server.1=192.168.64.1:2888:3888
      server.2=192.168.64.2:2888:3888
      server.3=192.168.64.3:2888:3888
  - path: /zookeeper/conf/README.txt
    content: |
      1. 修改 /zookeeper/myid文件，配置合适的zookeeper-id
      3. 修改/zookeeper/conf/zoo.cfg文件，配置合适的server地址
      4. 重新加载zookeeper service
          sudo systemctl daemon-reload
          sudo systemctl start zookeeper
          systemctl enable zookeeper
  - path: /etc/systemd/system/zookeeper.service
    owner: root:root
    content: |
      [Unit]
      Description=Zookeeper Daemon
      Documentation=http://zookeeper.apache.org
      Requires=network.target
      After=network.target

      [Service]    
      Type=forking
      WorkingDirectory=/opt/zookeeper
      User=zookeeper
      Group=zookeeper
      ExecStart=/opt/zookeeper/bin/zkServer.sh start /zookeeper/conf/zoo.cfg 
      ExecStop=/opt/zookeeper/bin/zkServer.sh stop /zookeeper/conf/zoo.cfg
      ExecReload=/opt/zookeeper/bin/zkServer.sh restart /zookeeper/conf/zoo.cfg
      TimeoutSec=30
      Restart=on-failure

      [Install]
      WantedBy=default.target

runcmd:
  - mkdir /zookeeper/data &&  mkdir /zookeeper/logs && chown -R zookeeper:zookeeper /zookeeper
  - [ wget, "https://mirrors.estointernet.in/apache/zookeeper/zookeeper-3.7.0/apache-zookeeper-3.7.0-bin.tar.gz", -O, /zookeeper/apache-zookeeper-3.7.0-bin.tar.gz ]
  - tar -xf /zookeeper/apache-zookeeper-3.7.0-bin.tar.gz -C /opt/
  - mv /opt/apache-zookeeper-3.7.0-bin/ /opt/zookeeper && chown -R zookeeper:zookeeper /opt/zookeeper
  - sed -i 's/^zookeeper.log.dir=\.$/zookeeper.log.dir=\/zookeeper\/logs/g' conf/log4j.properties 


